server.port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/profile

logging:
  file:
    max-size: 500MB
    path: logs
  pattern.rolling-file-name: ${logging.file.path}/logs.old/spring.%d{yyyy-MM-dd}.%i.log.gz
  pattern:
    dateformat: dd-MM-yyyy HH:mm:ss.SSS - %msg %n
    console: "%black(%d{ISO8601}) %highlight(%-5level) [%blue(%t)] %green(%C{1.}): %msg%n%throwable"
    file: "%black(%d{ISO8601}) %highlight(%-5level) [%blue(%t)] %green(%C{1.}): %msg%n%throwable"
  level:
    root: info
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: debug